[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_lend_borrow = "6EYYcsG5A1GpABbuaLJ1VWxhWavNfK1CVhWi1hyTPoJ3"

[programs.devnet]
nft_lend_borrow = "6EYYcsG5A1GpABbuaLJ1VWxhWavNfK1CVhWi1hyTPoJ3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/mahmud/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
